name: "Hello"
description: "Says hello"
inputs:
  who-to-greet:
    description: "Who we are greeting"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}

