name: Build and Test

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - master
      - main
  # workflow_dispatch:
  #   inputs:
  #     git_branch:
  #       description: 'Branch - The HEAD of this Branch will be the reference Commit'
  #       required: true
  #       default: master
  #     environment:
  #       description: 'Environment where the above HEAD should be deployed'
  #       required: true
  #       default: master
  #     author:
  #       description: 'GH Username of PR Author - Not Required if the PR Author is You'
  #       required: false

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      # - name: Fail
      #   run: exit 1

      - name: Build Test Image
        id: build
        run: |
          make build-test

      - uses: LouisBrunner/checks-action@v1.6.2
        with:
          name: Check Build Success
          conclusion: ${{ steps.build.outcome }}

      - name: Run Test Image
        run: |
          make run-test

      - uses: LouisBrunner/checks-action@v1.6.2
        with:
          name: Check Test Success
          conclusion: ${{ steps.build.outcome }}



